### PR TITLE
Jnt-55

### PR DESCRIPTION
**Pull request by hmdesai89**
Describe Addresses calls AutoUpdateDB method which clears anomaly between ec2 db and cassandra database. Calling DescribeAddresses in associate-address and release-address.

### CODE REVIEW

**Comment by gdpak** [comment]
Harsh, Why validate_db is not getting called from associate_address and disassociate_address ?
Also remove LOG_ERR change as Basil is committing it as part of another bug.
Please write script to validate your changes and share the script path along with script run on dev-envionment.

Also some minor comments
1) Don't put JNT-ids into code. Code will become overtime messy full of JNT-ID. Well written comments should suffice as you have already done.
2) Write function description before def <>
3) Newline diffs should be removed

**Comment by gdpak** [comment]
Please commit your script here - https://github.com/JioCloudVPC/scripts.git

**Comment by hmdesai89** [comment]
Hi Deepak,

Please see comments inline

validate_db is called in release address and associate address (line 284 and 358 respectively). I have not added that in disassociate address as it internally calls db cleanup method (_disassociate_address_item). 

I will take care of rest of comments and re-commit the code

**Comment by hmdesai89** [comment]
updated PR as per request.

**Pull request merged**
